# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
  tags:
      include:
        - release/*  


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: false

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet 7'
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore NuGet packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'LeaderAnalyticsFeed'
    includeNuGetOrg: true

- script: |
    npm install npm@8.3.1 -g
  displayName: Install specific version of npm

- script: |
    cd Blog/ClientApp
    npm --version
  displayName: 'verify npm version'

- script: |
    cd Blog/ClientApp
    npm install
  displayName: 'npm install'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    customCommand: run build
    workingDir: LeaderAnalytics.Vyntix.Web/ClientApp

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'DotNet publish'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingdirectory) --self-contained'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: 'AzureRmWebAppDeployment@4'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'All Azure Services'
    appType: webApp
    WebAppName: 'VyntixWeb'
    UseWebDeploy: true
    packageforLinux: '$(Build.ArtifactStagingDirectory)/*.zip'